### ISSUE TITLE
Pallet Manager Returns Version 0.0.1

### ISSUE THREAD

**Issue by keith8496** [haydendonald/atem-connection-nodered#1]
The pallet manager in Node-RED is installing version 0.0.1.
Version 0.0.1 is listed on https://flows.nodered.org/node/atem-connection-nodered.

I struggled for a while until I realized that what had been installed didn't match your GitHub repo. I installed version 0.2.1 from the command line and things are starting to work.

Thank you for your work on this. I like the way you created "directAction" as a wrapper to all of the existing functionality in atem-connection.

**Comment by haydendonald** [comment]
Hi @keith8496 thanks for letting me know about that! NodeRed changed it so I have to manually trigger an update. I have done that now the latest version should show on the pallet soon 😊
